image: hdlc/sim

variables:
  PNR_SEED: 1
  TOOLCHAIN_VERSION: v1.5.6
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - ./scripts/prepare-system-deps.sh
  - ./scripts/prepare.sh

test:
  stage: build
  script:
   - ./scripts/run-tests.sh
  artifacts:
    paths: ["test/pytest_report.html", "test/sim_build/*"]

benchmark:
  stage: build
  script:
    - ./scripts/download-riscv-toolchain.sh
    - ./scripts/find-riscv-toolchain.sh > env
    - source ./env
    - ./scripts/run-benchmark.sh

build-arty:
  stage: build
  image: gcr.io/hdl-containers/conda/f4pga/xc7/a50t
  variables:
    BASH_ENV: /usr/local/etc/profile.d/conda.sh
  script:
    - ./scripts/download-riscv-toolchain.sh
    - ./scripts/find-riscv-toolchain.sh > env
    - source ./env
    - ./scripts/build-arty.sh
  artifacts:
    paths: ["hw/build/digilent_arty/gateware/digilent_arty.bit"]
